---
default_install_hook_types: [ pre-commit ]
default_stages: [ pre-commit ]

exclude: ^docs/|^docs_output/|^profiling/flamegraph/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [ "--fix=lf" ]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.1
    hooks:
      - id: editorconfig-checker
        # clang-format already checks C++ files, cmake-format checks CMake files
        exclude: |
          (?x)^(
            LICENSE|
            .*\.md|
            .*\.cpp|
            .*\.hpp|
            .*\.cmake|
            CMakeLists\.txt
          )$

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [ pyyaml ]

  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        files: \.nix$

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [ "-i" ]

      - id: clang-tidy
        args: [ "-p=.", "--warnings-as-errors=*" ]
        exclude: ^(third_party|external)/.*$
