version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "Alexander Antipov"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**/.gitkeep", "**/*.lock", "CHANGELOG.md"]
precedence = "override"
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CODE_OF_CONDUCT.md"
precedence = "override"
SPDX-FileCopyrightText = "Coraline Ada Ehmke"
SPDX-License-Identifier = "CC-BY-4.0"
