[files]
extend-exclude = [
  # === templates-base =========================================================
  "*.lock",
  "LICENSES/",
  "CHANGELOG.md",
  # === end templates-base =====================================================
  # === templates-lang-cpp =====================================================
  "build/",
  "**/_deps/**",
  # === end templates-lang-cpp =================================================
]
