include_guard(GLOBAL)

macro(setup_ccache)
  if(${PROJECT_NAME}_ENABLE_CCACHE)
    find_program(CCACHE_PROGRAM ccache)
    if(CCACHE_PROGRAM)
      set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    endif()
  endif()
endmacro()
